# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: pretty

# Server config
source:  docs
destination:  _gh_pages
host: 0.0.0.0
port: 9001
url: http://bolteam.github.io/slabs/
baseurl: /slabs
encoding: UTF-8

gems:
  - jekyll-sitemap

# Custom vars
current_version: 1.0.0
repo: https://github.com/Bolteam/slabs

download:
  source:  https://github.com/Bolteam/slabs/archive/v1.0.0.zip
  dist:    https://github.com/Bolteam/slabs/releases/download/v1.0.0/slabs-1.0.0-dist.zip
